### ISSUE TITLE
Backquote words formatting

### ISSUE THREAD

**Issue by youngjoon-lee** [canstand/compost#3]
Hi @canstand

I’ve been really enjoying using Compost. Thanks a lot. 

One thing I want to ask is how to change the display format of backtick words. 

When I type something with backticks like \`hello\`. It is displayed as ** \`hello\`**. But, I want to find the way how to make it displayed as `hello`. I don’t want backticks are displayed, and I want it has a gray background color. 

Could you point me out how to change your theme for this?
Thank you.

**Comment by canstand** [comment]
It‘’s the default style for inline code of [tailwindcss-typography](https://github.com/tailwindlabs/tailwindcss-typography/blob/a86e6015694c3435ff6cef84f3dd61b81adf26e1/src/styles.js#L1536C1-L1541C11).

You can override this style in your own `tailwindcss.config.js`.
